services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    depends_on:
      - postgres-db
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres-db:5432/main_db
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
    volumes:
      - ./flyway/migrations:/flyway/sql
    command: -schemas=userservice,trackingservice migrate

  userservice:
    image: userservice:latest  # Ensure this image is built or modify to use a Dockerfile
    build:
      context: ./userservice
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/main_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"

  trackingservice:
    image: trackingservice:latest  # Ensure this image is built or modify to use a Dockerfile
    build:
      context: ./trackingservice
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/main_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8082"

volumes:
  postgres_data:
