name: Maven Build and Test for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [trackingservice, userservice]

    steps:
      # Step 1: Fazer o checkout do código do repositório
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Configurar o JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Usando Eclipse Temurin como distribuição
          java-version: '22'

      # Step 3: Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Navegar até a pasta do microsserviço e executar mvn test
      - name: Run Maven tests for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn test

      # Step 5: Navegar até a pasta do microsserviço e executar mvn package
      - name: Build with Maven for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -DskipTests
